[default]

# PACKAGE NAME
APPNAME = 'AWS_CODES'

# DIR TO SAVE LOGS
DIR_SAVE_LOGS = 'LOGS'

# FILENAME TO SAVE LOGS
LOG_FILENAME = 'LOG_AWS_CODES.log'

# LOGGING LEVEL
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'DEBUG'

# LOGGER INIT VARIABLE
LOGGERS = {}

[development]